### ISSUE TITLE
Classes in <li>, <a> tags

### ISSUE THREAD

**Issue by STOWouters** [ahmet2106/pico-navigation#3]
I'm wondering if there's a way to provide classes for `<li>` and/or `<a>` tags using `config.php`? Something as:

``` php
$config['at_navigation']['li_class'] = 'nav-item';
$config['at_navigation']['a_class'] = 'nav-link';
```

If it's already there, please could you update the readme? Otherwise, I would like to request this as a new feature in the next version :)

**Comment by ahmet2106** [comment]
thanks for your interest. added feature in newest commit 540f2d37ccb199c940e31719f3f35e0523fb1275

**Comment by STOWouters** [comment]
great! thanks.
