### ISSUE TITLE
the quick preview in default theme

### ISSUE THREAD

**Issue by liuzhiwei** [ahmet2106/pico-navigation#6]
You said in readme “I redesigned the style of the default theme for a quick preview. The output is like this:”

Could you share your solution? I want to do the same like you.

Sorry to raise this questions by issue, but I really don't know how to contact with you.

**Comment by ahmet2106** [comment]
i dunno if the default theme has changed, otherwise my theme files are in this repo:
https://github.com/ahmet2106/pico-navigation/tree/master/themes/default

but do not forget to install the plugin :) thats required

**Comment by liuzhiwei** [comment]
Thanks for your answer. but my site still won't like your screenshot after merging your changes for default theme and adding your plugin. Could you help to look at http://tjnote.sinaapp.com/ ? Thanks a lot

**Comment by jessebobrien** [comment]
I'm wondering if the default theme in Pico has changed? I just created a fresh install, activated at_navigation, and while I do have a series of UL's and LI's, they don't display a horizontal layout (just a simple bulleted list). I copied down the latest style.css, index.html, and min.js file as you indicated above, but it's not displayed correctly. Other than the instructions in the readme.md file, are any further steps required to make the css display appropriately?

**Comment by ahmet2106** [comment]
@liuzhiwei did u really implement the plugin with the shortcode at_navigation? doesnt looks like a custom navigation :)

@jessebobrien i'll have a look

**Comment by ahmet2106** [comment]
oh yeah you both are right! @liuzhiwei please update the whole default folder in themes with the one in this repo

@liuzhiwei @jessebobrien add this line to your config.php:
`$config['at_navigation']['class'] = 'nav';`

Just updated the repo with the description, thanks!

**Comment by liuzhiwei** [comment]
Thanks ahmet2106!  it works now by adding it.

```
    $config['at_navigation']['class'] = 'nav';
```

Thanks for your help
